# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiTiendita' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiTiendita

  target 'MiTienditaTests' do
    inherit! :search_paths
    # Pods for testing
  end
	pod 'Alamofire'

  target 'MiTienditaUITests' do
    # Pods for testing
  end

end
